name: Build Gradle project

on:
  push:
    tags:
      - "V*"

jobs:
  build-gradle-project:
    runs-on: windows-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Build with Gradle
      run: |
         ./gradlew bootJar
    - name: Upload jar
      run: |
          echo "done!"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/tourguide-0.0.1-SNAPSHOT.jar
       


