name: Build Gradle project

on:
  push:
    tags:
      - "V*"

jobs:
  build-gradle-project:
    runs-on: windows-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Build with Gradle
      run: |
         ./gradlew bootJar
    - name: Ls the dir
      run: ls
    - name: Ls the dir
      run: tree build /F
    - name: Create Log file
      run: git log --pretty=format:"%cd %s" --grep="Completed" > gitlog.txt
      shell: bash
    - name: Upload jar
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/tourguide-0.0.1-SNAPSHOT.jar
        asset_name: currentRelease.zip
        asset_content_type: application/zip
    - name: Ls the dir
      run: ls
    - name: Ls the dir
      run: tree build /F
       


